interface JsonToGoResult {
  go: string;
  error?: string;
}

interface JsonToGoOptions {
  inline?: boolean;
  customTag?: string;
  omitempty?: boolean;
  usePointers?: boolean;
}

type OmitemptyMap = Record<string, boolean>;

export default function jsonToGo(
  json: string,
  typename?: string,
  options: JsonToGoOptions = {}
): JsonToGoResult {
  let data;
  let customTag: string | undefined;

  try {
    data = JSON.parse(json.replace(/\.0/g, ".1"));
  } catch (e) {
    return {
      go: "",
      error: e.message
    };
  }

  try {
    customTag = parseCustomTag(options.customTag);
  } catch (e) {
    return {
      go: "",
      error: e.message
    };
  }

  const rootType = format(typename || "AutoGenerated");
  const useOmitempty = options.omitempty !== false;
  const usePointers = options.usePointers === true;

  if (options.inline === false) {
    return {
      go: generateNonInlineTypes(
        data,
        rootType,
        customTag,
        useOmitempty,
        usePointers
      )
    };
  }

  return {
    go: generateInlineTypes(
      data,
      rootType,
      customTag,
      useOmitempty,
      usePointers
    )
  };
}

function generateInlineTypes(
  scope: unknown,
  typename: string,
  customTag?: string,
  useOmitempty = true,
  usePointers = false
) {
  let tabs = 0;

  return "type " + typename + " " + parseScope(scope);

  function parseScope(currentScope: unknown): string {
    if (typeof currentScope === "object" && currentScope !== null) {
      if (Array.isArray(currentScope)) {
        let sliceType;
        const scopeLength = currentScope.length;

        for (let i = 0; i < scopeLength; i++) {
          const thisType = goType(currentScope[i]);
          if (!sliceType) sliceType = thisType;
          else if (sliceType !== thisType) {
            sliceType = mostSpecificPossibleGoType(thisType, sliceType);
            if (sliceType === "interface{}") break;
          }
        }

        if (sliceType === "struct") {
          const allFields = {};

          for (let i = 0; i < scopeLength; i++) {
            const keys = Object.keys(currentScope[i]);
            for (const k in keys) {
              const keyname = keys[k];
              if (!(keyname in allFields)) {
                allFields[keyname] = {
                  value: currentScope[i][keyname],
                  count: 0
                };
              }

              allFields[keyname].count++;
            }
          }

          const keys = Object.keys(allFields);
          const struct = {};
          const omitempty = {};

          for (const k in keys) {
            const keyname = keys[k];
            const elem = allFields[keyname];

            struct[keyname] = elem.value;
            omitempty[keyname] = elem.count !== scopeLength;
          }
          return applyPointersToType(
            "[]" + parseStruct(struct, omitempty),
            usePointers
          );
        }

        if (sliceType === "slice") {
          if (!scopeLength) {
            return applyPointersToType("[]interface{}", usePointers);
          }
          return applyPointersToType(
            "[]" + parseScope(currentScope[0]),
            usePointers
          );
        }

        return applyPointersToType(
          "[]" + (sliceType || "interface{}"),
          usePointers
        );
      }

      return parseStruct(currentScope as Record<string, unknown>);
    }
    return applyPointersToType(goType(currentScope), usePointers);
  }

  function parseStruct(
    structScope: Record<string, unknown>,
    omitempty?: OmitemptyMap
  ) {
    let parsed = "struct {\n";
    ++tabs;
    const keys = Object.keys(structScope);
    for (const i in keys) {
      const keyname = keys[i];
      parsed +=
        indent(tabs) +
        format(keyname) +
        " " +
        parseScope(structScope[keyname]) +
        " " +
        buildStructTag(
          keyname,
          useOmitempty || (omitempty && omitempty[keyname]),
          customTag
        ) +
        "\n";
    }
    --tabs;
    parsed += indent(tabs) + "}";
    return parsed;
  }

  function indent(indentTabs: number) {
    let text = "";
    for (let i = 0; i < indentTabs; i++) text += "\t";
    return text;
  }
}

function generateNonInlineTypes(
  scope: unknown,
  typename: string,
  customTag?: string,
  useOmitempty = true,
  usePointers = false
) {
  const usedTypeNames = new Set<string>();
  const typeDefinitions: string[] = [];

  const rootTypeName = reserveTypeName(typename);
  const rootScopeType = goType(scope);
  if (rootScopeType === "struct") {
    createStructType(rootTypeName, scope as Record<string, unknown>);
  } else if (rootScopeType === "slice") {
    typeDefinitions.push(
      "type " +
        rootTypeName +
        " " +
        parseArray(scope as unknown[], rootTypeName + "Item")
    );
  } else {
    typeDefinitions.push(
      "type " +
        rootTypeName +
        " " +
        applyPointersToType(rootScopeType, usePointers)
    );
  }

  return typeDefinitions.join("\n\n");

  function reserveTypeName(baseName: string) {
    let name = format(baseName || "AutoGenerated");
    if (!name) name = "AutoGenerated";
    if (!usedTypeNames.has(name)) {
      usedTypeNames.add(name);
      return name;
    }

    let suffix = 2;
    while (usedTypeNames.has(name + suffix)) suffix++;
    const unique = name + suffix;
    usedTypeNames.add(unique);
    return unique;
  }

  function createStructType(
    typeName: string,
    value: Record<string, unknown>,
    omitempty?: OmitemptyMap
  ) {
    const insertAt = typeDefinitions.length;
    typeDefinitions.push("");

    const keys = Object.keys(value || {});
    const lines = keys.map(keyname => {
      const fieldName = format(keyname);
      const fieldType = parseNonInlineScope(
        value[keyname],
        typeName + fieldName,
        typeName + fieldName + "Item"
      );

      return (
        "\t" +
        fieldName +
        " " +
        fieldType +
        " " +
        buildStructTag(
          keyname,
          useOmitempty || (omitempty && omitempty[keyname]),
          customTag
        )
      );
    });

    typeDefinitions[insertAt] =
      "type " + typeName + " struct {\n" + lines.join("\n") + "\n}";
  }

  function parseNonInlineScope(
    value: unknown,
    structTypeBaseName: string,
    arrayItemTypeBaseName: string
  ): string {
    if (typeof value === "object" && value !== null) {
      if (Array.isArray(value)) {
        return parseArray(value, arrayItemTypeBaseName);
      }
      const structTypeName = reserveTypeName(structTypeBaseName);
      createStructType(structTypeName, value as Record<string, unknown>);
      return applyPointersToType(structTypeName, usePointers);
    }
    return applyPointersToType(goType(value), usePointers);
  }

  function parseArray(
    arrayScope: unknown[],
    arrayItemTypeName: string
  ): string {
    let sliceType;
    const scopeLength = arrayScope.length;

    for (let i = 0; i < scopeLength; i++) {
      const thisType = goType(arrayScope[i]);
      if (!sliceType) sliceType = thisType;
      else if (sliceType !== thisType) {
        sliceType = mostSpecificPossibleGoType(thisType, sliceType);
        if (sliceType === "interface{}") break;
      }
    }

    if (sliceType === "struct") {
      const allFields = {};

      for (let i = 0; i < scopeLength; i++) {
        const keys = Object.keys(arrayScope[i] as Record<string, unknown>);
        for (const k in keys) {
          const keyname = keys[k];
          if (!(keyname in allFields)) {
            allFields[keyname] = {
              value: (arrayScope[i] as Record<string, unknown>)[keyname],
              count: 0
            };
          }
          allFields[keyname].count++;
        }
      }

      const keys = Object.keys(allFields);
      const struct = {};
      const omitempty = {};
      for (const k in keys) {
        const keyname = keys[k];
        const elem = allFields[keyname];
        struct[keyname] = elem.value;
        omitempty[keyname] = elem.count !== scopeLength;
      }

      const itemType = reserveTypeName(arrayItemTypeName);
      createStructType(itemType, struct, omitempty);
      return applyPointersToType("[]" + itemType, usePointers);
    }

    if (sliceType === "slice") {
      if (!scopeLength) {
        return applyPointersToType("[]interface{}", usePointers);
      }
      return applyPointersToType(
        "[]" +
          parseNonInlineScope(
            arrayScope[0],
            arrayItemTypeName,
            arrayItemTypeName + "Item"
          ),
        usePointers
      );
    }

    return applyPointersToType(
      "[]" + (sliceType || "interface{}"),
      usePointers
    );
  }
}

function parseCustomTag(customTag?: string) {
  const tag = (customTag || "").trim();
  if (!tag) return undefined;

  if (!/^[A-Za-z_][A-Za-z0-9_-]*$/.test(tag)) {
    throw new Error(
      "Custom tag name must start with a letter/underscore and contain only letters, numbers, _ or -."
    );
  }

  return tag;
}

function buildStructTag(
  jsonKey: string,
  withOmitempty: boolean | undefined,
  customTag?: string
) {
  const tagValue = jsonKey + (withOmitempty ? ",omitempty" : "");
  let tag = 'json:"' + tagValue + '"';

  if (customTag) {
    tag += " " + customTag + ':"' + tagValue + '"';
  }

  return "`" + tag + "`";
}

function applyPointersToType(typeName: string, usePointers: boolean) {
  if (!usePointers) return typeName;

  let baseType = typeName;
  let arrayPrefix = "";
  while (baseType.startsWith("[]")) {
    arrayPrefix += "[]";
    baseType = baseType.slice(2);
  }

  if (!baseType || baseType === "interface{}" || baseType.startsWith("*")) {
    return arrayPrefix + baseType;
  }

  return arrayPrefix + "*" + baseType;
}

function format(str: string) {
  if (!str) return "";
  if (str.match(/^\d+$/)) str = "Num" + str;
  else if (str.charAt(0).match(/\d/)) {
    const numbers = {
      "0": "Zero_",
      "1": "One_",
      "2": "Two_",
      "3": "Three_",
      "4": "Four_",
      "5": "Five_",
      "6": "Six_",
      "7": "Seven_",
      "8": "Eight_",
      "9": "Nine_"
    };
    str = numbers[str.charAt(0)] + str.substr(1);
  }
  return toProperCase(str).replace(/[^a-z0-9]/gi, "") || "NAMING_FAILED";
}

function goType(val: unknown) {
  if (val === null) return "interface{}";

  switch (typeof val) {
    case "string":
      if (/\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(\.\d+)?(\+\d\d:\d\d|Z)/.test(val)) {
        return "time.Time";
      }
      return "string";
    case "number":
      if (val % 1 === 0) {
        if (val > -2147483648 && val < 2147483647) return "int";
        return "int64";
      }
      return "float64";
    case "boolean":
      return "bool";
    case "object":
      if (Array.isArray(val)) return "slice";
      return "struct";
    default:
      return "interface{}";
  }
}

function mostSpecificPossibleGoType(typ1: string, typ2: string) {
  if (typ1.substr(0, 5) === "float" && typ2.substr(0, 3) === "int") {
    return typ1;
  }
  if (typ1.substr(0, 3) === "int" && typ2.substr(0, 5) === "float") {
    return typ1;
  }
  return "interface{}";
}

function toProperCase(str: string) {
  const commonInitialisms = [
    "API",
    "ASCII",
    "CPU",
    "CSS",
    "DNS",
    "EOF",
    "GUID",
    "HTML",
    "HTTP",
    "HTTPS",
    "ID",
    "IP",
    "JSON",
    "LHS",
    "QPS",
    "RAM",
    "RHS",
    "RPC",
    "SLA",
    "SMTP",
    "SSH",
    "TCP",
    "TLS",
    "TTL",
    "UDP",
    "UI",
    "UID",
    "UUID",
    "URI",
    "URL",
    "UTF8",
    "VM",
    "XML",
    "XSRF",
    "XSS"
  ];

  return str
    .replace(/(^|[^a-zA-Z])([a-z]+)/g, function(_unused, sep, frag) {
      if (commonInitialisms.indexOf(frag.toUpperCase()) >= 0) {
        return sep + frag.toUpperCase();
      }
      return sep + frag[0].toUpperCase() + frag.substr(1).toLowerCase();
    })
    .replace(/([A-Z])([a-z]+)/g, function(_unused, sep, frag) {
      if (commonInitialisms.indexOf(sep + frag.toUpperCase()) >= 0) {
        return (sep + frag).toUpperCase();
      }
      return sep + frag;
    });
}
